# Generated by Django 4.2.1 on 2023-05-23 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='category_name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='category_description')),
            ],
            options={
                'verbose_name': 'category_name',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='product_name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='product_description')),
                ('image', models.ImageField(upload_to='images')),
                ('price', models.IntegerField(verbose_name='product_price')),
                ('time_create', models.DateField(auto_now_add=True, verbose_name='creation_date')),
                ('time_update', models.DateField(auto_now=True, verbose_name='update_date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
            ],
            options={
                'verbose_name': 'product_name',
                'verbose_name_plural': 'products',
                'ordering': ['time_create', 'name'],
            },
        ),
    ]
