# Generated by Django 4.2.1 on 2023-06-15 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='blog_name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='blog_slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='blog_description')),
                ('image', models.ImageField(upload_to='images')),
                ('time_create', models.DateField(auto_now_add=True, verbose_name='creation_date')),
                ('is_published', models.BooleanField(default=True)),
                ('view_count', models.IntegerField(default=0, verbose_name='counts_views')),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blogs',
                'ordering': ['time_create', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='category_name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='category_description')),
            ],
            options={
                'verbose_name': 'category_name',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='user_contact_name')),
                ('surname', models.CharField(max_length=100, verbose_name='surname_contact_name')),
                ('email', models.CharField(max_length=100, verbose_name='user_email')),
                ('feedback', models.CharField(max_length=100, verbose_name='user_feedback')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='product_name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='product_description')),
                ('image', models.ImageField(upload_to='images')),
                ('price', models.IntegerField(verbose_name='product_price')),
                ('time_create', models.DateField(auto_now_add=True, verbose_name='creation_date')),
                ('time_update', models.DateField(auto_now=True, verbose_name='update_date')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='product_slug')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
            ],
            options={
                'verbose_name': 'product_name',
                'verbose_name_plural': 'products',
                'ordering': ['time_create', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=100, verbose_name='title_name')),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'verbose_name': 'version',
                'verbose_name_plural': 'versions',
            },
        ),
    ]
