# Generated by Django 4.2.1 on 2023-05-22 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='category_name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='category_description')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='product_name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='product_description')),
                ('image', models.ImageField(upload_to='media')),
                ('price', models.IntegerField(verbose_name='product_price')),
                ('time_create', models.DateField(auto_now_add=True, verbose_name='product_create')),
                ('time_update', models.DateField(auto_now=True, verbose_name='product_update')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
            ],
        ),
    ]
