# Generated by Django 4.2.1 on 2023-06-27 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['time_create', 'name'], 'permissions': (('change_name', 'can change name of product'),), 'verbose_name': 'product_name', 'verbose_name_plural': 'products'},
        ),
    ]
