# Generated by Django 4.2.1 on 2023-06-27 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['time_create', 'name'], 'verbose_name': 'product_name', 'verbose_name_plural': 'products'},
        ),
    ]
